### ISSUE TITLE
Renaming a page breaks the build

### ISSUE THREAD

**Issue by simonw** [simonw/til#24]
The rename in b9f613dd7386cdcc7ab97e6734acf86a0c42cad6 broke things: https://github.com/simonw/til/runs/1059759359?check_suite_focus=true

```
Traceback (most recent call last):
Rendered HTML for github/dependencies-graphql-api.md
  File "build_database.py", line 98, in <module>
    build_database(root)
Rendered HTML for bash/loop-over-csv.md
  File "build_database.py", line 90, in build_database
Rendered HTML for readthedocs/custom-subdomain.md
    record.update(all_times[path])
Rendered HTML for readthedocs/readthedocs-search-api.md
KeyError: 'cloudrun/gcloud-run-services-list.md'
```
It looks like the `all_times = created_changed_times(repo_path)` function can't handle files that were renamed.

**Comment by simonw** [comment]
For the moment I'm going to remove the file in one commit then add it again in a second commit.

**Comment by simonw** [comment]
I am going to try to remember not to rename pages.
