### ISSUE TITLE
RuntimeError('There is no current event loop in thread %r.')

### ISSUE THREAD

**Issue by simonw** [simonw/til#48]
https://til.simonwillison.net/ site is down at the moment:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/9599/180585291-b3565178-53c6-45b1-9ff3-78bfe2c9033b.png">

Logs at https://vercel.com/datasette/simon-til/9SYmpgw4ExnTbRLnsevw5zXXTRgb/functions show:

`[ERROR] RuntimeError: There is no current event loop in thread 'MainThread'.Traceback (most recent call last):  File "/var/task/vc__handler__python.py", line 453, in vc_handler    lifespan = Lifespan(__vc_module.app)  File "/var/task/vc__handler__python.py", line 308, in __init__    self.loop = get_event_loop()  File "/var/task/vc__handler__python.py", line 184, in get_event_loop    return asyncio.get_event_loop()  File "/var/lang/lib/python3.9/asyncio/events.py", line 642, in get_event_loop    raise RuntimeError('There is no current event loop in thread %r.'`

**Comment by simonw** [comment]
This could be a new `datasette-publish-vercel` bug.

**Comment by simonw** [comment]
Yup, just deployed https://test-if-vercel-publish-broken.vercel.app/ with this and I'm getting the same error:

    datasette publish vercel fixtures.db --project 'test-if-vercel-publish-broken'
